#!/bin/sh


echo "STAGE=.$STAGE
PORT=1729
REACT_APP_HTTP_BACKEND_URL=http://$IP/pyrog
REACT_APP_RIVER_URL=http://$IP/river
REACT_APP_PAGAI_URL=http://$IP/pagai
REACT_APP_CLEANING_SCRIPTS_URL=http://$IP/scripts
REACT_APP_FHIR_API_URL=http://$IP/api
"