export const AUTH_TOKEN = 'ARKHN_AUTH_TOKEN';
export const {
  REACT_APP_HTTP_BACKEND_URL: HTTP_BACKEND_URL,
  REACT_APP_FHIRPIPE_URL: FHIRPIPE_URL,
  REACT_APP_CLEANING_SCRIPTS_URL: CLEANING_SCRIPTS_URL,
  REACT_APP_ENGINE_BACKEND_URL: ENGINE_BACKEND_URL
} = process.env;
