FROM node:10.15-alpine
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
ENV NODE_ENV docker
RUN wget https://arkhn.org/pyrog_dev_static.zip
RUN unzip -o pyrog_dev_static.zip
RUN rm pyrog_dev_static.zip
CMD yarn run wait-on http://pyrog:4000 && yarn run test --coverage
