FROM node:10.15-alpine
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
ENV NODE_ENV docker
CMD yarn run wait-on http://pyrog:4000 && env $(cat .env.staging) yarn run test
