export const ownerList : string[] = [
    'ICSF',
    'SYSTEM'
]

export const tableList : string[] = [
    'PATIENT',
    'JOURNAL',
    'MEDICATION'
]

export const firstNameColumnsExample : any = [ { owner: 'GROUP',
    table: 'STATUS',
    column: 'ID',
    rows:
     [ 'Maëlys',
       'Adrien',
       'Théo',
       'Tom',
       'Rayan',
       'Adrien',
       'Sacha',
       'Maëlys',
       'Mathéo',
       'Chloé',
       'Ambre',
       'Nicolas',
       'Romain',
       'Noa',
       'Yanis',
       'Lola',
       'Maëlle',
       'Julien',
       'Charlotte',
       'Louis' ] },
  { owner: 'ID',
    table: 'PHONE',
    column: 'UPDATEDAT',
    rows:
     [ 'Mohamed',
       'Maëlys',
       'Carla',
       'Anaïs',
       'Noah',
       'Lucas',
       'Axel',
       'Léo',
       'Raphaël',
       'Romane',
       'Nathan',
       'Lina',
       'Jeanne',
       'Evan',
       'Julien',
       'Romain',
       'Théo',
       'Lena',
       'Raphaël',
       'Mathilde' ] },
  { owner: 'CATEGORY',
    table: 'TOKEN',
    column: 'TITLE',
    rows:
     [ 'Chloé',
       'Maeva',
       'Elisa',
       'Yanis',
       'Hugo',
       'Juliette',
       'Anaïs',
       'Emilie',
       'Ethan',
       'Julien',
       'Hugo',
       'Adrien',
       'Théo',
       'Pierre',
       'Alice',
       'Chloé',
       'Lou',
       'Yanis',
       'Maëlle',
       'Julien' ] },
  { owner: 'TOKEN',
    table: 'STATUS',
    column: 'NAME',
    rows:
     [ 'Louis',
       'Jeanne',
       'Lucie',
       'Lena',
       'Nicolas',
       'Axel',
       'Maeva',
       'Célia',
       'Arthur',
       'Camille',
       'Antoine',
       'Adam',
       'Ines',
       'Laura',
       'Zoe',
       'Louis',
       'Lucas',
       'Ines',
       'Lilou',
       'Clara' ] },
  { owner: 'TITLE',
    table: 'TOKEN',
    column: 'COMMENT',
    rows:
     [ 'Adrien',
       'Mathilde',
       'Lola',
       'Arthur',
       'Maeva',
       'Océane',
       'Manon',
       'Quentin',
       'Manon',
       'Mohamed',
       'Rayan',
       'Julie',
       'Louna',
       'Jules',
       'Jade',
       'Manon',
       'Lina',
       'Jules',
       'Julien',
       'Anaïs' ] },
  { owner: 'TOKEN',
    table: 'UPDATEDAT',
    column: 'TITLE',
    rows:
     [ 'Mohamed',
       'Paul',
       'Justine',
       'Benjamin',
       'Alexandre',
       'Laura',
       'Louna',
       'Romane',
       'Lucas',
       'Quentin',
       'Alexandre',
       'Mattéo',
       'Pauline',
       'Mathis',
       'Gabriel',
       'Louise',
       'Justine',
       'Antoine',
       'Elisa',
       'Charlotte' ] },
  { owner: 'EMAIL',
    table: 'TOKEN',
    column: 'PASSWORD',
    rows:
     [ 'Ines',
       'Carla',
       'Gabriel',
       'Maëlle',
       'Maëlys',
       'Mael',
       'Jules',
       'Rayan',
       'Romane',
       'Antoine',
       'Louis',
       'Manon',
       'Maxime',
       'Kylian',
       'Anaïs',
       'Yanis',
       'Noémie',
       'Julie',
       'Mael',
       'Mélissa' ] },
  { owner: 'TOKEN',
    table: 'UPDATEDAT',
    column: 'NAME',
    rows:
     [ 'Adam',
       'Alicia',
       'Lou',
       'Maxime',
       'Alexandre',
       'Anaïs',
       'Sacha',
       'Julie',
       'Evan',
       'Kylian',
       'Julien',
       'Mattéo',
       'Mathilde',
       'Hugo',
       'Jeanne',
       'Victor',
       'Maëlys',
       'Louna',
       'Lisa',
       'Mélissa' ] },
  { owner: 'STATUS',
    table: 'CATEGORY',
    column: 'CATEGORY',
    rows:
     [ 'Alexis',
       'Pauline',
       'Clémence',
       'Alicia',
       'Juliette',
       'Eva',
       'Romane',
       'Marie',
       'Mathilde',
       'Charlotte',
       'Gabriel',
       'Benjamin',
       'Thomas',
       'Carla',
       'Alexis',
       'Noa',
       'Manon',
       'Lena',
       'Mathéo',
       'Clara' ] },
  { owner: 'PASSWORD',
    table: 'TITLE',
    column: 'TOKEN',
    rows:
     [ 'Lucas',
       'Alexis',
       'Victor',
       'Ambre',
       'Emilie',
       'Maëlle',
       'Raphaël',
       'Manon',
       'Thomas',
       'Jules',
       'Léo',
       'Enzo',
       'Océane',
       'Jade',
       'Julien',
       'Justine',
       'Louise',
       'Lucie',
       'Rayan',
       'Lina' ] } ]

export const filePathColumnsExample : any = [ { owner: 'AVATAR',
    table: 'TOKEN',
    column: 'UPDATEDAT',
    rows:
     [ 886,
       93449,
       46635,
       72038,
       33338,
       90621,
       96726,
       96854,
       66629,
       12989,
       47347,
       7622,
       31390,
       81659,
       16676,
       2140,
       65692,
       41872,
       95702,
       33957 ] },
  { owner: 'TOKEN',
    table: 'GROUP',
    column: 'NAME',
    rows:
     [ 19863,
       95032,
       90593,
       67237,
       96223,
       89223,
       97563,
       99293,
       91641,
       76123,
       67440,
       37452,
       80806,
       86765,
       17241,
       73967,
       10056,
       60820,
       37000,
       53903 ] },
  { owner: 'AVATAR',
    table: 'TITLE',
    column: 'CATEGORY',
    rows:
     [ 35914,
       90164,
       36633,
       53619,
       4031,
       30219,
       50862,
       90128,
       18399,
       40988,
       67642,
       14425,
       49983,
       28438,
       89942,
       62325,
       16061,
       77224,
       84056,
       58987 ] },
  { owner: 'UPDATEDAT',
    table: 'ID',
    column: 'UPDATEDAT',
    rows:
     [ 30580,
       85690,
       15630,
       95104,
       68354,
       69329,
       64072,
       16100,
       7416,
       55490,
       48604,
       74910,
       50205,
       95046,
       1585,
       12366,
       635,
       10343,
       88822,
       31690 ] } ]
